export const questions = {
  sql: [
    "what is sql?",
    "how use the SQL ?",
    "History of SQL ?",
    "What is Data ?",
    "what is Database?",
    "What is DBMS ?",
    "What is RDBMS ?",
    "Difference Between DBMS and RDBMS ?",
    "What is Datatype ?",
    "What is Char datatype ?",
    "What is varchar datatype ?",
    "Difference Between char vs varchar datatype ?",
    "What is Number Datatype ?",
    "What is Date Datatype ?",
    "",
  ],
  java: [
    "what is langauge?",
    "what is programming language?",
    "how to bulid a language?",
    "what is JDK and what is IDK?",
    "History of Java?",
    "What is Token?",
    "what is Identifier?",
    "what is keyword?",
    "Tell me 50 keyword of java?",
    "what is literals?",
    "What is Seperator?",
    "Artchitecure of java?",
    "What is JDK",
    "What is JRE",
    "What is JVM",
    "What is JIT",
    "Why java is platform independend?",
    "what is concatination?",
    "what is class?",
    "what is commmands?",
    "what is method?",
    "why we go for method?",
    "what is method with parameter?",
    "what is method with return?",
    "what is java?",
    "what is varible",
    "Difference between Global and local variable",
    "what is static",
    "What is non-static",
    "what is Block",
    "why static has one copy",
    "why non-static has multiply copy",
    "what is object",
    "what is Reference Variable?",
    "What is Constructor?",
    "What is this keyword?",
    "What is composition?",
    "what is address of object?",
    "what is pass by value?",
    "what is pass by Reference?",
    "what is method overloading",
  ],
};
